service: gaia-spider-lambdas

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: cn-north-1
  endpointType: regional
  role: arn:aws:iam::836317673605:role/serverless-role-for-lambda

  layers:
  - ${cf:gaia-${opt:layerName}-${opt:layerVersion}-${opt:stage,self:provider.stage}.layerName}

functions:

  gaia-spider-simulator:
    handler: lambdas.simulator.lambda_handler
    name: gaia-spider-simulator-${opt:stage,self:provider.stage}
    description: simulator
    events:
    - http:
        path: /simulator
        method: post
        authorizer: authorizer

  authorizer:
    handler: lambdas.authorizer.lambda_handler
    name: gaia-spider-authorizer-${opt:stage,self:provider.stage}