service: gaia-spider-lambdas

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: cn-north-1
  endpointType: regional
  role: arn:aws:iam::836317673605:role/serverless-role-for-lambda

  layers:
  - ${cf:gaia-${opt:layerName}-${opt:layerVersion}-${opt:stage,self:provider.stage}.layerName}

functions:

  compute:
    handler: lambdas.consumer.lambda_handler
    name: gaia-spider-kinesis-consumer-${opt:stage,self:provider.stage}
    events:
      - stream:
          type: kinesis
          arn: arn:aws-cn:kinesis:cn-north-1:836317673605:stream/prod.mirror.update
          consumer: true
