service: gaia-spider-lambdas

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: cn-north-1

  layers:
  - ${cf:gaia-${opt:layerName}-${opt:layerVersion}-${opt:stage,self:provider.stage}.layerName}

functions:

  compute:
    handler: lambdas.consumer.lambda_handler
    events:
      - stream:
          type: kinesis
          arn: arn:aws-cn:kinesis:cn-north-1:836317673605:stream/prod-mirror-update
